/* Deeper, textiles-specific explanation layered onto the source-grounded core theory. */
(() => {
  const depth = {
    '1.1': `<p>A useful brief leaves room for design decisions while making the purpose unmistakable. It should not quietly prescribe a colour, exact shape or construction method unless that fact comes from the approved project instructions. Ask: <em>What must this solution achieve, and what is still mine to decide?</em></p><div class="callout"><strong>Design lens:</strong> Separate the need from a preferred solution. "Carry a packed lunch securely" is a need; "use a zip" is only one possible response.</div>`,
    '1.2': `<p>Consider the user before, during and after use. Before lunch, the bag must be packed and carried. During lunch, it must open and give access to the contents. Afterwards, it may need cleaning, drying and storage. A feature that works at one moment can create a problem at another.</p><p>Use a simple trade-off statement: <strong>adding this feature may improve...</strong> but it may also <strong>increase...</strong>. This prevents a design from becoming a collection of untested extras.</p>`,
    '1.3': `<p>Strong criteria name a feature, an expected performance and a way to observe it. Different criteria need different evidence: a carry trial for comfort, a capacity check for fit, close inspection for stitch quality, and user feedback for ease of opening. Constraints should describe actual boundaries, not excuses.</p><ul><li><strong>Criterion:</strong> what success looks like.</li><li><strong>Test:</strong> how it will be checked.</li><li><strong>Evidence:</strong> what will be recorded.</li></ul>`,
    '2.1': `<p>Textile products are systems, not just pieces of fabric. They can combine an outer material, lining, thread, closure, handle, decoration and stiffening or insulation where approved. Each component has a job, and the way components interact affects comfort, durability, care and production.</p><p>When investigating a product, move from <em>name it</em> to <em>explain it</em>: identify the component, state its function, name the property that supports that function and note a possible limitation.</p>`,
    '2.2': `<p>Woven structures usually show two sets of yarns crossing at right angles. Knitted structures are formed from connected loops and often stretch more easily. Non-wovens may be bonded, compressed or felted rather than made from interlaced yarns. Structure does not determine every property, but it gives useful clues.</p><div class="callout"><strong>Look closely:</strong> inspect an edge, stretch the sample gently as directed and compare both surfaces. Evidence from the actual material is stronger than guessing from appearance.</div>`,
    '2.3': `<p>Material selection is a balancing decision. A thick material may offer body but be harder to fold accurately. An absorbent textile may feel familiar but take longer to dry. A tightly woven material may fray less than another sample but still require an approved edge finish.</p><p>Use a weighted comparison only when the criteria are clear. Give more importance to properties that directly affect function and safe construction, then explain why the chosen balance suits the brief.</p>`,
    '3.1': `<p>A waste audit turns a broad environmental issue into countable evidence. Record what appears in a real packed lunch, how often each item is used and which items are genuinely avoidable. Do not assume every disposable item has the same impact or that every reusable replacement will be used consistently.</p><p>The strongest action targets a frequent item, suits the user and includes a routine for washing, returning or storing the replacement so that reuse actually occurs.</p>`,
    '3.2': `<p>Life-cycle decisions are connected. A highly durable material may require more resources to produce, but a long service life can spread that impact over many uses. A repairable closure may extend use, while a product that is difficult to clean may be abandoned early.</p><ul><li>Reduce offcuts through thoughtful layout.</li><li>Design for care and repeated handling.</li><li>Record repair possibilities.</li><li>Avoid claims that cannot be supported.</li></ul>`,
    '3.3': `<p>Personal action needs a baseline and a check. A baseline records what happens now; the action states what will change; the check records whether it happened. For example, a student might count disposable carrier bags for one week, use the reusable bag for four weeks and compare the two records.</p><div class="callout"><strong>Claim carefully:</strong> report what your evidence shows. One product can reduce a particular repeated item without solving every lunch-waste problem.</div>`,
    '4.1': `<p>Safe sewing is a repeated decision cycle: <strong>stop, set up, check, operate, stop safely</strong>. The operator controls the pace and should never use speed to hide uncertainty. If thread tangles, fabric shifts or a sound changes, remove pressure from the control, stop and follow the demonstrated response.</p><p>Machine-specific threading, bobbin placement and settings are Teacher to confirm. The general rule is consistent: do not guess around moving parts.</p>`,
    '4.2': `<p>Think in zones. The sewing zone contains the machine and fabric being controlled. The sharp-tool zone keeps scissors, pins and needles visible and stored. The heat zone keeps the iron stable and away from cords, hands and materials until it is used under the approved routine.</p><p>A tidy bench is not just about appearance. It reduces reaching across hazards, makes missing pins easier to notice and creates space to rotate or support fabric without pulling it.</p>`,
    '4.3': `<p>A useful equipment record links each item to a task. "Scissors" is incomplete; "fabric scissors used to cut the approved textile pieces" explains function and evidence. Photographs should show the actual classroom item at a readable scale, with a caption that names what the viewer should notice.</p><div class="callout"><strong>Source boundary:</strong> record actual project materials after they are supplied or confirmed. Do not fill gaps with products found online.</div>`,
    '5.1': `<p>Good research compares patterns across products. One existing bag might solve access well, another might organise the contents, and another may demonstrate a useful visual identity. Record both strengths and limitations so research does not become advertising.</p><p>Transform research by combining principles rather than copying forms. A clear opening from one product and a compact carrying idea from another can inspire a new response, provided the final design fits the brief and approved construction pathway.</p>`,
    '5.2': `<p>Divergent thinking deliberately creates distance between options. Change one or more meaningful variables: overall form, opening direction, closure type, carrying method, proportion, pocket arrangement or surface design. Then annotate each option with function, user benefit and possible production challenge.</p><div class="callout"><strong>Four-concept test:</strong> cover the colour. If the concepts still look and function differently, the set is genuinely varied.</div>`,
    '5.3': `<p>Convergent thinking narrows the options using evidence. A decision matrix can help, but the numbers do not make the decision automatically. Explain why important criteria deserve more weight and check whether a high score hides a serious practical limitation.</p><p>A final communication should include the selected view, useful detail views, labels, a colour/material indication and notes that distinguish confirmed decisions from Teacher to confirm construction information.</p>`,
    '6.1': `<p>A sewing machine creates a lockstitch by coordinating motion and thread. The needle carries the upper thread through the fabric; the lower thread is supplied from the bobbin area; the mechanism forms an interlock between them. The exact hook and bobbin system is machine-specific, but both threads must be correctly positioned.</p><p>Thread path is functional: guides manage direction, tension devices control delivery and the take-up action manages slack. Skipping one stage can change the stitch even when the thread reaches the needle.</p>`,
    '6.2': `<p>The presser foot and feed dogs work as a pair. The foot applies downward control while the feed dogs rise, grip and advance the fabric in small steps. The needle plate supports the material around the needle opening. Pulling the fabric fights this system and can distort the seam or place sideways force on the needle.</p><div class="callout"><strong>Operator focus:</strong> watch the seam guide and the path ahead. The needle area stays in peripheral view for safety.</div>`,
    '6.3': `<p>Controls should be learned by function, not by memorising one diagram. The handwheel positions the needle under the demonstrated method; the reverse control may secure stitching; stitch selectors and length controls change stitch formation; a speed control may limit the maximum pace. Location and operation vary.</p><p>Build a classroom-machine guide from direct observation. Include a photograph or drawing, part name, function and one safe-use note. Record model-specific values only after teacher confirmation.</p>`,
    '7.1': `<p>Setup is a verification task. Trace the complete upper path, check the needle-area threading direction, confirm the bobbin orientation and bring threads to the demonstrated starting position. Then make a sample on approved scrap material before using project pieces.</p><p>When a fault appears, return to the whole setup rather than changing several controls at once. One change at a time makes the cause easier to identify and prevents random settings from creating a second problem.</p>`,
    '7.2': `<p>Accuracy comes from preparation, vision and pace. Align the fabric before starting, lower the presser foot, position hands outside the needle zone and build speed gradually. Support the fabric so its weight does not drag the seam sideways.</p><ul><li>Look ahead along the seam guide.</li><li>Slow before corners or changes.</li><li>Stop before realigning.</li><li>Finish using the teacher-approved securing method.</li></ul>`,
    '7.3': `<p>Read both sides of a stitch sample. Balanced stitching has a consistent appearance without loose loops, skipped sections or fabric distortion. Loops can indicate a threading or setup issue; puckering may involve material, stitch choice, handling or setup; skipped stitches may require a teacher check of the needle and machine.</p><div class="callout"><strong>Safe diagnosis:</strong> describe the symptom first. Do not immediately blame tension or adjust a control that has not been demonstrated.</div>`,
    '8.1': `<p>Surface design should belong to the product. Use contrast so a motif is visible, repetition to create rhythm, scale to suit the available area and proportion so decoration supports rather than overwhelms the form. Negative space can be as important as filled space.</p><p>Test the design in context by placing a paper or fabric mock-up on the intended panel. A motif that looks balanced alone may clash with a seam, closure or handle once positioned on the bag.</p>`,
    '8.2': `<p>Applique quality depends on a chain of decisions: template accuracy, grain and fabric behaviour, cutting control, placement, temporary holding, edge treatment and stitching. The approved adhesive, pressing conditions and stitch method depend on the supplied materials and classroom process.</p><p>Simple shapes are not lesser designs. They can be easier to cut and control, more readable from a distance and more durable around edges than shapes with many tight corners.</p>`,
    '8.3': `<p>A sample is a small investigation. Keep the question focused: Does the colour contrast work? Can the curve be stitched with control? Does the edge remain flat? Record the setup, observe the result and change one feature before repeating when time allows.</p><div class="callout"><strong>Evidence language:</strong> write "the tight inside curve produced uneven spacing" rather than "it looked bad". Specific observations lead to specific improvements.</div>`,
    '9.1': `<p>A strong workplan groups the practical into preparation, assembly, construction, finishing, checking, evidence and cleanup. It also identifies dependencies: decoration may need to be completed before a panel is joined, and a closure position may need checking before permanent stitching.</p><p>Estimate time as a planning aid, then record actual progress. If the sequence changes, explain why. Exact pieces, dimensions, seam allowances and construction order remain controlled by the teacher-approved instructions.</p>`,
    '9.2': `<p>Use "measure or align twice, make once" before irreversible actions. Check right and wrong sides, direction of prints, matching edges, component orientation and the relationship between closures and openings. Compare the work to the approved plan, not to memory.</p><p>Accuracy does not mean hiding every correction. A well-recorded correction shows that the maker noticed evidence, protected the project and made a reasoned decision.</p>`,
    '9.3': `<p>Quality control is strongest at planned hold points. Pause after cutting, before permanent joining, after the first important seam, before attaching a closure and before final finishing. At each hold point, decide whether to proceed, correct or ask for help.</p><div class="callout"><strong>Photographic evidence:</strong> include the whole relevant stage, enough detail to see the feature and a caption explaining the decision or quality check. A photo without explanation is incomplete evidence.</div>`,
    '10.1': `<p>A fair test controls what can be controlled and records what actually happened. Capacity can be checked with the intended items; closure security through an approved carry routine; finish through close inspection; and ease of use through a short user trial. Do not create unsafe water, heat or load tests.</p><p>Write the method before the result. This makes it harder to change the test simply because the product performed differently from the prediction.</p>`,
    '10.2': `<p>Evaluation is an argument supported by evidence. Name the criterion, report the observation, make a judgement and explain the design feature that contributed to the result. Include limitations because they reveal where the evidence is incomplete or where performance is mixed.</p><div class="callout"><strong>Evaluation sentence:</strong> The bag [met / partly met / did not meet] the criterion because the test showed..., which was influenced by...</div>`,
    '10.3': `<p>A specific improvement should be possible to act on. It may refine a feature, alter a sequence, improve a quality checkpoint or change how evidence is collected. The strongest improvement is connected directly to a test result rather than added as a general wish.</p><p>Reflection looks at growth as well as the product: planning, safe practice, machine control, response to problems, independence and the ability to justify decisions. Use one real moment as evidence for each claim.</p>`
  };

  COURSE_MODULES.forEach(module => {
    module.sections.forEach((section, index) => {
      section.html += depth[`${module.id}.${index + 1}`] || '';
    });
  });
})();
